# Site
repository: devlnull/me
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Amirhossein Ghorbani
title: Senior Software Engineer
email: amqorbani@hotmail.com
# email_title: Email (Email title override)
phone: 989168086844
# phone_title: Phone (Phone title override)
website: devlnull.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: devlnull
github_username:  devlnull
stackoverflow_username: "5301677"
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: amirhossein-ghorbani
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username: 

# Additional icon links
additional_links:
- title: Download Resume
  icon: fa fa-download
  url: https://drive.google.com/file/d/1emXBsULMA7Iie5ilYRu8GZ5NnBHNorZq/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile-picture-1-1.jpg
about_content: |
        Software engineer with over 10 years of experience building reliable, high-performance systems across complex domains like travel, booking, and financial services.
        I enjoy working through architectural challenges and designing systems that scale well and remain maintainable over time.
        In past roles, I’ve taken the lead on critical projects, collaborated with cross-functional teams, and helped guide engineering decisions that align with business goals. 
        I’m comfortable weighing technical trade-offs and navigating the messier parts of system design.
        I’m always learning — from books, open-source projects, and other engineers’ solutions — and I try to bring that curiosity into everything I build.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Alibaba Travels Co
        sub_title: Technical Lead
        caption: 2024 - NOW
        link: https://alibaba.ir
        quote:
        description: | # this will include new lines to allow paragraphs
          • Designed and delivered a Buy Now, Pay Later (BNPL) service tailored for B2B customers in the travel and tourism space, solving real-world challenges around payment flexibility and delayed settlements.
          • Mentored a team of seven engineers, supported their technical growth, and helped shape our team roadmap and day-to-day development practices.
          • Improved system performance and delivery workflows, contributing to a 20% increase in GMV and helping establish the product as a strong player in the B2B market.
      - layout: left
        title: Alibaba Travels Co
        sub_title: Senior Software Engineer
        caption: 2023 - 2024
        link: https://alibaba.ir
        quote:
        description: | # this will include new lines to allow paragraphs
          • I played a pivotal role as the lead software engineer in the B2B Merge project, successfully combining a separate B2B travel project into our B2C project.
           This effort significantly reduced costs for the company and led to major changes in our microservices structure to better understand the B2B system. <br />
          • Improved existing platform and base project issues and bugs through comprehensive refactoring,
           introducing innovative solutions, and seamlessly integrating them into base projects to enhance overall performance. <br />
      - layout: left
        title: Alibaba Travels Co
        sub_title: Software Engineer
        caption: 2021 - 2023
        link: https://alibaba.ir
        quote:
        description: | # this will include new lines to allow paragraphs
          • Developed a survey service to manage rate and reviews for vertical services with over 10K surveys per day. <br />
          • Successfully refactored the leading bus ticketing software in the country, achieving more than 100% increase in
          performance and setting a new record of one sale per second. <br />
          • Led the implementation of promotions for bus services, enabling users to receive discounts on different routes and
          managing stakeholder expectations. <br />
          • Streamlined the CI/CD pipeline by implementing a new solution that utilized Docker caching layers, resulting in a
          200% faster delivery process. <br />
          • Implemented domain events and reduced coupling in the bus service components, resulting in a more efficient
          and scalable system. <br />
      - layout: left
        title: SepidSystem
        sub_title: Software Engineer
        caption: 2019 - 2021
        link: https://sepidsystem.com
        quote:
        description: | # this will include new lines to allow paragraphs
          • I have refactored Safe Deposit Boxes software (Used by most of Iranian banks) to achieve better processes and
          workflows. <br />
          • Developed a dynamic workflow engine module for the Safe Deposit Boxes service, enabling real-time design of
          custom workflows to fit each bank'’'s specific needs. <br />
          • Created a Migration tool to facilitate offline database conversions from old to new versions in banks’ data centers. <br />
          • Implemented a biometric-based user authorization solution, requiring users to utilize a fingerprint or face detection device to access their active contract box. <br />
      - layout: left
        title: 1st
        sub_title: Backend Developer
        caption: 2017 - 2019
        link: https://1st.ir
        quote:
        description: | # this will include new lines to allow paragraphs
          • Generated workflow statistics and analytics reports using complex SQL queries.
          • Built and maintained the Payment Service Dashboard, enabling sales teams and administrators to configure business rules and manage critical components of the payment flow
      - layout: left
        title: 1st
        sub_title: Intern Developer
        caption: 2015 - 2017
        link: https://1st.ir
        quote:
        description: | # this will include new lines to allow paragraphs
          • Collaborated with the IT department to develop internal web applications supporting the college’s dining plan system, improving usability and efficiency for staff and students.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Shamsipour Technical and Vocational College
        sub_title: BA Software Engineering
        caption: 2017 - 2019
        quote:
        description: |
          Attending the **best technical college** in the country was an incredible opportunity for me to learn and expand my knowledge in Software Engineering. 
          Throughout my academic studies, I was exposed to a range of exciting and interesting topics, including **algorithms** and **data structures**, **operating systems**, **databases**, **network systems**, **math** and **logical circuits**.
          These academic topics have **proved** invaluable in my **technical career**, allowing me to apply my **theoretical knowledge** to **real-world situations** and develop practical solutions to complex problems. 
          I truly believe that my academic studies provided me with a strong foundation that has allowed me to excel in my professional career as a software developer.
      - layout: left
        title: Dezful Technical and Vocational College
        sub_title: Technical Diploma in Software Engineering
        caption: 2017 - 2019
        quote:
        description:

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Technologies** :  .NET Stack, Git, T-SQL, Relational Databases, Redis, ORMs <br />
      **Proficiency in** :  Software Architectures, System Design, Algorithm and Data Structures, Design Pattern, Refactoring, Architectural Patterns, Microservices, Agile Methodologies, TDD, DDD, BDD, UML <br />
      **Tools** : Docker, Kubernetes, RabbitMQ, Elastic, Grafana, K6, TFS, Jira, Microsoft Teams
  - title: Languages
    layout: text
    content: |
      **English**: Professional Working Proficiency <br />
      **Persian**: Native

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      At the young age of 14, I discovered my passion for technology and began **teaching myself programming** through **books.** <br />
      This passion for programming continued to grow, leading me to pursue a degree in Software Engineering through **college** and **university**. <br />
      In my free time, I enjoy playing **games** and **going for runs**, but studying new technology and **reading books** related to my field is a major hobby of mine. <br />
      I find that **music** and **coffee** are my go-to sources of energy, helping me accomplish great things and stay **focused** on my goals. <br />
# Footer
footer_show_references: false
references_title: Amirhossein Ghorbani

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
